# Generated by Django 3.0 on 2023-05-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('1', 'Eco'), ('2', 'Sustainability')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
