# Generated by Django 3.0 on 2023-05-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_name',
            field=models.CharField(default='earth.jpg', max_length=250),
            preserve_default=False,
        ),
    ]
